import { NgModule } from '@angular/core';
// import { CommonModule } from '@angular/common';
import {
  DxPopupModule,
  DxDataGridModule,
  DxFormModule,
  DxButtonModule,
  DxTextBoxModule,
  DxSelectBoxModule,
  DxTextAreaModule,
  DxNumberBoxModule,
  DxAutocompleteModule,
  DxButtonGroupModule,
  DxSwitchModule,
  DxListModule,
  DxDateBoxModule,
  DxTagBoxModule,
  DxDropDownBoxModule,
  DxTabsModule,
  // DxNavBarModule,
  DxTabPanelModule,
  // DxTreeViewModule,
  // DxTemplateModule,
  // DxDrawerModule,
  // DxToolbarModule,
  DxCheckBoxModule,
  DxValidatorModule,
  // DxValidationSummaryModule,
  DxAccordionModule,
  DxContextMenuModule,
  // DxSliderModule,
  // DxResponsiveBoxModule,
  // DxMenuModule,
  // DxColorBoxModule,
  DxRadioGroupModule,
  DxLookupModule,
  DxTooltipModule,
  DxSliderModule,
  DxGalleryModule
} from 'devextreme-angular';



@NgModule({
  declarations: [],
  imports: [
    // CommonModule
    DxPopupModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxTextBoxModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxNumberBoxModule,
    DxAutocompleteModule,
    DxSwitchModule,
    DxListModule,
    DxDateBoxModule,
    DxTagBoxModule,
    DxDropDownBoxModule,
    DxTabsModule,
    // DxNavBarModule,
    DxTabPanelModule,
    // DxTreeViewModule,
    // DxTemplateModule,
    // DxDrawerModule,
    // DxToolbarModule,
    DxCheckBoxModule,
    DxValidatorModule,
    // DxValidationSummaryModule,
    DxAccordionModule,
    // DxSliderModule,
    // DxResponsiveBoxModule,
    // DxMenuModule,
    // DxColorBoxModule,
    DxRadioGroupModule,
    DxContextMenuModule,
    DxButtonGroupModule,
    DxTooltipModule,
    DxSliderModule,
    DxGalleryModule
  ],
  exports: [
    DxPopupModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxTextBoxModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxNumberBoxModule,
    DxAutocompleteModule,
    DxSwitchModule,
    DxListModule,
    DxDateBoxModule,
    DxTagBoxModule,
    DxDropDownBoxModule,
    DxTabsModule,
    // DxNavBarModule,
    DxTabPanelModule,
    // DxTreeViewModule,
    // DxTemplateModule,
    // DxDrawerComponent, DxDrawerModule,
    // DxToolbarModule,
    DxCheckBoxModule,
    DxValidatorModule,
    // DxValidationSummaryModule,
    DxAccordionModule,
    // DxSliderModule,
    // DxResponsiveBoxModule,
    // DxMenuModule,
    // DxColorBoxModule,
    DxRadioGroupModule,
    DxContextMenuModule,
    DxLookupModule,
    DxButtonGroupModule,
    DxTooltipModule,
    DxSliderModule,
    DxGalleryModule
  ]
})
export class DevextremeModule { }
